version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: refynd_dev
      POSTGRES_USER: refynd
      POSTGRES_PASSWORD: refynd_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - refynd-dev-network

  # Redis for Bull Queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - refynd-dev-network

  # Backend API (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://refynd:refynd_dev@postgres:5432/refynd_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret_change_in_production
      - API_PORT=8000
    ports:
      - "8000:8000"
      - "9229:9229"  # Node.js debugger port
    depends_on:
      - postgres
      - redis
    networks:
      - refynd-dev-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    command: ["npm", "run", "dev"]

  # Background Job Worker (Development)
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://refynd:refynd_dev@postgres:5432/refynd_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret_change_in_production
    depends_on:
      - postgres
      - redis
    networks:
      - refynd-dev-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "worker:dev"]

  # Frontend (Development with hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_DEV_MODE=true
    ports:
      - "3000:3000"
    networks:
      - refynd-dev-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  # Adminer for database management
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - refynd-dev-network
    depends_on:
      - postgres

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - refynd-dev-network
    depends_on:
      - redis

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  refynd-dev-network:
    driver: bridge